map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom
sensor_timeout: 0.5
two_d_mode: true

frequency: 20

odom0: odometry/vel/bag
odom0_config: [false, false, false,
               false, false, false,
               true, false, false,
               false, false, true,
               false, false, false]
odom0_differential: false # with GPS, must be false
odom0_queue_size: 10

# odom1: odometry/gps/bag
# odom1_config: [true, true, false,
#                false, false, false,
#                false, false, false,
#                false, false, false,
#                false, false, false]
# odom1_differential: false # with GPS, must be false
# odom1_queue_size: 10

imu0: middle_middle_imu/imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
              # true, true, true]
imu0_differential: false # with GPS, must be false
imu0_queue_size: 10
imu0_nodelay: 10
imu0_remove_gravitational_acceleration: true


print_diagnostics: true
