map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom
sensor_timeout: 0.1
two_d_mode: true

frequency: 50

magnetic_declination_radians: 0.0043
yaw_offset: 1.5707963

odom0: odometry/gps
odom0_config: [true, true, false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false # with GPS, must be false
odom0_queue_size: 10

imu0: imu
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              false, false, false]
imu0_differential: false # with GPS, must be false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true


print_diagnostics: true
