## USB port
port: /dev/ttyUSB0
#port: /dev/USBimu


##### Calibration ####
### accelerometer
accel_x_min: -261.0
accel_x_max: 313.0
accel_y_min: -274.0
accel_y_max: 261.0
accel_z_min: -305.0
accel_z_max: 266.0

### magnetometer
# standard calibration
magn_x_min: -279.0
magn_x_max: 595.0
magn_y_min: -466.0
magn_y_max: 524.0
magn_z_min: -434.0
magn_z_max: -7.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [114.019, 6.51021, -21.1150]
magn_ellipsoid_transform: [[0.860251, 0.0593519, 0.0584897], [0.0593519, 0.845807, 0.0973261], [0.0584897, 0.0973261, 0.859812]]


# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 5.72
gyro_average_offset_y: 50.61
gyro_average_offset_z: 13.83
